# Generated by Django 4.2.4 on 2023-08-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('genre', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=30)),
                ('episodes', models.IntegerField()),
                ('rating', models.FloatField()),
                ('members', models.IntegerField()),
            ],
        ),
    ]
